name: simpo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.2.2=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.22.2=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310hff52083_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.0.13=h7f8727e_1
  - packaging=24.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - platformdirs=4.2.1=pyhd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - python=3.10.14=h955ad1f_0
  - python_abi=3.10=2_cp310
  - pyzmq=25.1.2=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py310h5764c6d_3
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.29.2
      - aiofiles==23.2.1
      - aiohttp==3.9.4
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.6.0
      - anthropic==0.25.6
      - anyio==4.3.0
      - appdirs==1.4.4
      - arch==5.3.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - bert-score==0.3.13
      - bitsandbytes==0.41.2.post2
      - blis==0.7.11
      - catalogue==2.0.10
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.16.0
      - commonmark==0.9.1
      - confection==0.1.4
      - contourpy==1.2.1
      - coverage==7.5.3
      - cpm-kernels==1.0.11
      - cycler==0.12.1
      - cymem==2.0.8
      - dataclasses==0.6
      - dataclasses-json==0.6.4
      - datasets==2.18.0
      - deepspeed==0.12.2
      - diffusers==0.28.0
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - dotmap==1.3.30
      - einops==0.7.0
      - evaluate==0.4.0
      - exceptiongroup==1.2.1
      - execnet==2.1.1
      - expt==0.4.2
      - fairscale==0.4.13
      - fastapi==0.110.1
      - fastcore==1.5.42
      - ffmpy==0.3.2
      - filelock==3.13.4
      - flash-attn==2.5.7
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fschat==0.2.34
      - fsspec==2024.2.0
      - ghapi==1.0.5
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==3.50.2
      - gradio-client==0.6.1
      - grpcio==1.62.1
      - h11==0.14.0
      - hf-transfer==0.1.6
      - hjson==3.1.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.22.2
      - idna==3.7
      - importlib-metadata==5.2.0
      - importlib-resources==6.4.0
      - iniconfig==2.0.0
      - jinja2==3.1.3
      - joblib==1.4.0
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - langcodes==3.3.0
      - llm-blender==0.0.2
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markdown2==2.4.13
      - markupsafe==2.1.5
      - marshmallow==3.21.1
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - murmurhash==1.0.10
      - mypy-extensions==1.0.0
      - networkx==3.3
      - nh3==0.2.17
      - ninja==1.11.1.1
      - nltk==3.8.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - openai==0.28.1
      - openrlbenchmark==0.2.1a5
      - orjson==3.10.1
      - pandas==2.2.2
      - parameterized==0.9.0
      - pathtools==0.1.2
      - patsy==0.5.6
      - peewee==3.17.5
      - peft==0.7.1
      - pillow==10.3.0
      - pip==22.3.1
      - pluggy==1.5.0
      - preshed==3.0.9
      - prettytable==3.10.0
      - prompt-toolkit==3.0.43
      - property-cached==1.6.4
      - protobuf==3.20.1
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pycocoevalcap==1.2
      - pycocotools==2.0.7
      - pydantic==1.10.15
      - pydantic-core==2.18.1
      - pydub==0.25.1
      - pygments==2.17.2
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - pytest==8.2.1
      - pytest-cov==5.0.0
      - pytest-xdist==3.6.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.9
      - pytz==2024.1
      - pyyaml==6.0.1
      - ray==2.11.0
      - referencing==0.34.0
      - regex==2023.12.25
      - requests==2.31.0
      - responses==0.18.0
      - rich==11.2.0
      - rliable==1.0.8
      - rpds-py==0.18.0
      - safetensors==0.4.2
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.12.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - shortuuid==1.0.13
      - shtab==1.7.1
      - smart-open==6.4.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - spacy==3.7.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - starlette==0.37.2
      - statsmodels==0.14.2
      - svgwrite==1.4.3
      - sympy==1.12
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - thinc==8.2.3
      - threadpoolctl==3.4.0
      - tiktoken==0.6.0
      - tokenizers==0.15.2
      - tomli==2.0.1
      - toolz==0.12.1
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - tqdm==4.66.2
      - transformers==4.44.2
      - triton==2.2.0
      - trl==0.9.6
      - tueplots==0.0.4
      - typeguard==4.3.0
      - typer==0.9.4
      - typing-inspect==0.9.0
      - tyro==0.5.18
      - tzdata==2024.1
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - wandb==0.13.11
      - wasabi==1.1.2
      - wavedrom==2.0.3.post3
      - weasel==0.3.4
      - websockets==11.0.3
      - werkzeug==3.0.2
      - wget==3.2
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.19.1
